workflows:
  android:
    name: Android Build
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Regenerate Android structure
        script: |
          mkdir -p temp_flutter_project
          cd temp_flutter_project
          flutter create --platforms android pricepeek_temp
          cd ../
          cp -r temp_flutter_project/pricepeek_temp/android/* ./android/
          rm -rf temp_flutter_project
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk